on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  welcome:
    runs-on: ubuntu-latest
    
    steps:
      - name: Welcome Message
        run: echo "Welcome to our GitHub Actions workflow!"
        
  build:
    runs-on: ubuntu-latest
    needs: welcome
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Change to the desired .NET Core version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
    
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Change to the desired .NET Core version

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  sonarcloud:
    runs-on: ubuntu-latest
    needs: welcome
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Change to the desired .NET Core version

      - name: Restore dependencies
        run: dotnet restore
        
      - name: SonarCloud
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"SONAR_TOKEN" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ 91ed3117bf17d5736f806435ec3b4955e52b1483 }}"
          dotnet build --no-restore
          dotnet sonarscanner end /d:sonar.login="${{ 91ed3117bf17d5736f806435ec3b4955e52b1483 }}"
  
  
  publish:
    runs-on: ubuntu-latest
    needs: [test, sonarcloud]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Change to the desired .NET Core version

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish -c Release -o ./publish
        